export default constant = {
  FontWeight: {
    thin: '100',
    ultraLight: '200',
    light: '300',
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    heavy: '800',
    black: '900',
  },
  FontFamily: {
    fontFamily: 'Poppins',
  },
  FontSize: {
    title: 24,
    primaryText: 20,
    secondaryText: 15,
    placeholderText: 15,
    button: 20,
    validation: 15,
    logoText: 28,
    RadioText: 18,
    cardText: 16,
  },
  colors: {
    //   buttonbackground:'rgb(254,95,97);',
    white: '#FFFFFF',
    title: '#3B3B3B',
    secondaryText: '#606060',
    placeholderText: '#818181',
    placeholder: '#9F9F9F',
    greyBorder: '#A2A2A2',
    redBorder: '#FF0000',
    black: '#000000',
    inputcolor: '#E5E5E5',
    otpbox: '#F5F5F5',
    pinkBorder: '#FC3876',
    squareButtonOne: '#FFEEF0',
    squareButtonTwo: '#E5E5E5',
    GButtonText: '#3B3B3B',
    heading: '#3B3B3B',
    Radio: '#FF6B5B',
    underLine: '#F2F2F2',
    view: '#FC3876',
  },
  imagePath: {
    logoimage: require('../assets/images/logoimage.png'),
    writedata: require('../assets/images/icon/Writedata.png'),
    phone: require('../assets/images/icon/phone.png'),
    SUser: require('../assets/images/icon/SUser.png'),
    phone: require('../assets/images/icon/phone.png'),
    biglogin: require('../assets/images/icon/biglogin.png'),
    rightRedArrow: require('../assets/images/icon/rightRedArrow.png'),
    Sucess: require('../assets/images/icon/Sucess.png'),
    failed: require('../assets/images/icon/failed.png'),
    Notification: require('../assets/images/icon/Notification.png'),
    Request: require('../assets/images/icon/Request.png'),
    Diamond: require('../assets/images/icon/Diamond.png'),
    package: require('../assets/images/icon/package.svg'),
    profile: require('../assets/images/icon/smalluser.png'),
    roundMenu: require('../assets/images/icon/round.png'),
    tabProfile: require('../assets/images/icon/tabProfile.png'),
    bigUser: require('../assets/images/icon/bigUser.png'),
    splashscreen: require('../assets/images/Splash.png'),
  },
};
