const routeNames = {
  //Auth stack screen
  SPLASHSCREEN: 'Splashscreen',
  AGREETERMSCONDITION: 'AgreeTermsCondition',
  OTP: 'Otp',
  PHONENUMBER: 'PhoneNumber',
  INTROSLIDER: 'IntroSlider',
  SWIPESCREENS: 'SwipeScreens',
  GENDER: 'Gender',
  PROFESSION: 'Profession',
  NATIONALITY: 'Nationality',
  SKINCOLOR: 'SkinColor',
  RELIGIOUSCOMMITMENT: 'ReligiousCommitment',
  BODYSTRUCTURE: 'BodyStructure',
  SUPPORT: 'Support',
  MARITIALSTATUS: 'MaritialStatus',
  ABOUTYOURSELF: 'AboutYourself',

  //Home stack screen
  HOMESCREEN: 'HomeScreen',
  PEOPLE: 'People',
  NOTIFICATION: 'Notification',
  REQUESTCONTACT: 'RequestContact',
  PROFILE: 'Profile',
  SUBSCRIPTION: 'SubScription',
  SUBSCRIPTIONDETAILS: 'SubscriptionDetails',
  PACKAGESUCCESS: 'PackageSuccess',
  PACKAGEERROR: 'PackageError',
  DELETEACCOUNT: 'DeleteAccount',
  EDITNAME: 'EditName',
  REPORTPROBLEM: 'ReportProblem',
  APPNAVIGATOR: 'AppNavigator',
  MAINTERMSCONDITION: 'MainTermsCondition',
  LANGAUGE: 'Langauge',
  PROFILEDETAILS: 'ProfileDetails',
  VIEWPROFILE: 'ViewProfile',
  HISTORY: 'History',
};
export default routeNames;
